# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twitterbot.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TwitterBot(object):
    def setupUi(self, TwitterBot):
        TwitterBot.setObjectName("TwitterBot")
        self.centralwidget = QtWidgets.QWidget(TwitterBot)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(445, 350))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.url = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.url.setMinimumSize(QtCore.QSize(0, 20))
        self.url.setMaximumSize(QtCore.QSize(16777215, 40))
        self.url.setObjectName("url")
        self.verticalLayout.addWidget(self.url)
        self.pinLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pinLabel.setTextFormat(QtCore.Qt.AutoText)
        self.pinLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pinLabel.setObjectName("pinLabel")
        self.verticalLayout.addWidget(self.pinLabel)
        self.pinLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pinLine.setMinimumSize(QtCore.QSize(0, 20))
        self.pinLine.setText("")
        self.pinLine.setAlignment(QtCore.Qt.AlignCenter)
        self.pinLine.setObjectName("pinLine")
        self.verticalLayout.addWidget(self.pinLine)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.amountLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.amountLine.setMinimumSize(QtCore.QSize(0, 20))
        self.amountLine.setText("")
        self.amountLine.setFrame(True)
        self.amountLine.setAlignment(QtCore.Qt.AlignCenter)
        self.amountLine.setPlaceholderText("")
        self.amountLine.setClearButtonEnabled(False)
        self.amountLine.setObjectName("amountLine")
        self.verticalLayout.addWidget(self.amountLine)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.targetLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.targetLine.setMinimumSize(QtCore.QSize(0, 20))
        self.targetLine.setText("")
        self.targetLine.setAlignment(QtCore.Qt.AlignCenter)
        self.targetLine.setPlaceholderText("")
        self.targetLine.setObjectName("targetLine")
        self.verticalLayout.addWidget(self.targetLine)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.skipMutuals = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipMutuals.sizePolicy().hasHeightForWidth())
        self.skipMutuals.setSizePolicy(sizePolicy)
        self.skipMutuals.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.skipMutuals.setAutoFillBackground(False)
        self.skipMutuals.setChecked(True)
        self.skipMutuals.setObjectName("skipMutuals")
        self.horizontalLayout_3.addWidget(self.skipMutuals)
        self.stableMode = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stableMode.sizePolicy().hasHeightForWidth())
        self.stableMode.setSizePolicy(sizePolicy)
        self.stableMode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stableMode.setAutoFillBackground(False)
        self.stableMode.setChecked(True)
        self.stableMode.setObjectName("stableMode")
        self.horizontalLayout_3.addWidget(self.stableMode)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.followBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.followBtn.sizePolicy().hasHeightForWidth())
        self.followBtn.setSizePolicy(sizePolicy)
        self.followBtn.setAutoRepeat(False)
        self.followBtn.setDefault(False)
        self.followBtn.setFlat(False)
        self.followBtn.setObjectName("followBtn")
        self.horizontalLayout_2.addWidget(self.followBtn)
        self.unfollowBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unfollowBtn.sizePolicy().hasHeightForWidth())
        self.unfollowBtn.setSizePolicy(sizePolicy)
        self.unfollowBtn.setAutoRepeat(False)
        self.unfollowBtn.setDefault(False)
        self.unfollowBtn.setFlat(False)
        self.unfollowBtn.setObjectName("unfollowBtn")
        self.horizontalLayout_2.addWidget(self.unfollowBtn)
        self.stopBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBtn.sizePolicy().hasHeightForWidth())
        self.stopBtn.setSizePolicy(sizePolicy)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_2.addWidget(self.stopBtn)
        self.exitBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitBtn.sizePolicy().hasHeightForWidth())
        self.exitBtn.setSizePolicy(sizePolicy)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        TwitterBot.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TwitterBot)
        self.statusbar.setObjectName("statusbar")
        TwitterBot.setStatusBar(self.statusbar)

        self.retranslateUi(TwitterBot)
        QtCore.QMetaObject.connectSlotsByName(TwitterBot)

    def retranslateUi(self, TwitterBot):
        _translate = QtCore.QCoreApplication.translate
        TwitterBot.setWindowTitle(_translate("TwitterBot", "MainWindow"))
        self.label_3.setText(_translate("TwitterBot", "Verification URL:"))
        self.pinLabel.setText(_translate("TwitterBot", "PIN:"))
        self.label_2.setText(_translate("TwitterBot", "Amount:"))
        self.label_4.setText(_translate("TwitterBot", "Target:"))
        self.skipMutuals.setText(_translate("TwitterBot", "Skip mutual followers"))
        self.stableMode.setText(_translate("TwitterBot", "Stable mode"))
        self.followBtn.setText(_translate("TwitterBot", "Follow"))
        self.unfollowBtn.setText(_translate("TwitterBot", "Unfollow"))
        self.stopBtn.setText(_translate("TwitterBot", "Stop"))
        self.exitBtn.setText(_translate("TwitterBot", "Exit"))
        self.progressBar.setFormat(_translate("TwitterBot", "%p%"))

